# Generated by Django 2.2.16 on 2022-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221102_1539'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='user_favorite_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='user_shoppingcart_unique',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_recipe_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_recipe_unique'),
        ),
    ]
