# Generated by Django 2.2 on 2022-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscribe_user_author_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='user_author_unique',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author'),
        ),
    ]
